//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class kullanıcı_ogretmen
    {
        public int id { get; set; }
        [DisplayName("Kullanıcı Adı")]
        [MinLength(5, ErrorMessage = "Şifre minumum 5 karakterden oluşmalı")]
        public string KullaniciAd { get; set; }
        [DisplayName("Sifre")]
        [MinLength(3,ErrorMessage ="Şifre minumum 3 karakterden oluşmalı")]
        public string KullanıcıSifre { get; set; }
    }
}
