//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanıcı_ogrenci
    {
        public int id { get; set; }
        public Nullable<int> OgrenciNo { get; set; }
        public string KullanıcıSifre { get; set; }
    }
}
